apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::758151278751:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-100ARHYKLG5YE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::758151278751:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-18T17:06:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1653"
  uid: 8c692b8a-6809-406d-a100-138d6d07111d
